### ISSUE TITLE
Comments section is unreadable in Dark mode

### ISSUE THREAD

**Issue by arthurmadecprevost** [mindsers/mindsersit-blog#68]
While in Dark mode, the comment section is just unreadable : 
![Capture d’écran 2023-05-07 à 17 14 38](https://user-images.githubusercontent.com/50238555/236686202-69a6312b-0a34-45e9-af84-18671f2dd9f0.png)

**Comment by mindsers** [comment]
@arthurmadecprevost Hey! Thanks so much for opening a pull request!

I really appreciate you sending this over, I look at this bug ASAP. You can also submit a fix if you know how to do it.

**Comment by arthurmadecprevost** [comment]
Maybe you can take a look at this line : https://github.com/mindsersit/mindsers-blog/blob/20cd6296a37421e1d6a388a0b17db4081c3d5f24/post.hbs#L124
It may be the first step in the bug resolution.

**Comment by arthurmadecprevost** [comment]
https://ghost.org/docs/themes/helpers/comments/

Easier !!!
Just change the mode from "light" to "auto".

**Comment by mindsers** [comment]
It works indeed. Do you want to submit a PR or do you want me to do it ?

**Comment by arthurmadecprevost** [comment]
opened pull request #69

**Comment by arthurmadecprevost** [comment]
Hi @mindsers 
Is the issue resolved ? If so, we can close it now. 😉😁

**Comment by mindsers** [comment]
True this
